version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - java -version
      - gradle assemble
artifacts:
  files:
    - '**/*'
  base-directory: 'build/libs'