version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - java -version
      - ./gradlew test
      - ./gradlew assemble
artifacts:
  files:
    - '**/*.jar'
  base-directory: 'build/libs'