apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notesapi
  name: notesapi
spec:
  replicas: 3
  selector:
    matchLabels:
      app: notesapi
  strategy: {}
  template:
    metadata:
      labels:
        app: notesapi
    spec:
      containers:
      - image: leandro/notes:k8s
        imagePullPolicy: IfNotPresent
        name: notesapi
        resources: {}
        ports:
          - containerPort: 15000
status: {}
