apiVersion: v1
kind: Service
metadata:
  labels:
    app: notesapi-service
  name: notesapi-service
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 15000
  selector:
    app: notesapi
  type: LoadBalancer
status:
  loadBalancer: {}
