apiVersion: v1
kind: Service
metadata:
  name: {{ include "notesapi.fullname" . }}
  labels:
    {{- include "notesapi.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "notesapi.selectorLabels" . | nindent 4 }}
